---
# tasks file for ansible-Zoneminder
- name: yum | Installing required packages to system
  yum: name=pip state=latest

- name: python-pip | Installing required packages for mysql user and db modules
  pip: name=mysql-python state=latest
  
- include: zmrepo.yml
- include: zmconfig.yml
- include: mysql_config.yml
- include: phpconfig.yml
- include: httpdconfig.yml
- include: service_status.yml
...