---
# tasks file for ansible-Zoneminder
- name: yum | Installing required packages to system
  yum: name=pip state=latest

- name: python-pip | Installing required packages for mysql user and db modules
  pip: name=mysql-python state=latest

# zmrepo negates the need for EPEL and RPMFusion
# ref: http://www.zoneminder.com/wiki/index.php/CentOS#Zmrepo_-_A_ZoneMinder_repository_for_RPM_based_distros
- name: installing zmrepo 
  local_action: yum
       name={{ zmrepo_url_el6 }}
       disable_gpg_check=yes 
       state=latest
  when: ansible_os_family == "RedHat"

- name: installing ZoneMinder
  yum: name=zoneminder state=latest
  notify: start_mysql

- name: ensuring all required ZM services are enabled at boot
  service: name="{{ item }}" enabled=yes
  with_items:
    - mysqld
    - zoneminder
    - httpd

- include: mysql_config.yml
- include: phpconfig.yml
- include: httpdconfig.yml
- include: service_status.yml
...