---
# Configure php.ini file
# The only thing we want to modify now is the date.timezone param

- name: modifying php to support local_machine timezone configuration
  lineinfile: >
    state=present
    backrefs=yes
    dest=/etc/php.ini
    regexp=";date.timezone"
    line="date.timezone = {{ date_timezone }}" 
...