---
# This playbook will install and configure zoneminder
# Author: Nate Dobbs
#   * Supports ZM running with SElinux in ENFORCING mode
#   * Currently only supports EL6.x distros ( zmrepo limitation )

- name: installing ZoneMinder
  yum: name=zoneminder state=latest
  notify: start_mysql

- name: ensuring all required ZM services are enabled at boot
  service: name="{{ item }}" enabled=yes
  with_items:
    - mysqld
    - zoneminder
    - httpd
...