# ansible-role-zoneminder/handlers/main.yml
---
- name: start_db
  service: name="{{ zm_db }}" state=started

- name: secure_db
  command: "/root/mysql_secure"

- name: prompt_service_address
  debug: msg="ZoneMinder configuration complete, please visit http://{{ ansible_fqdn }}/zm to customize your install"
...